# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name Animation extends Resource

@export var name: String = ""
@export var length: float = 0.0
@export var loop: bool = false
@export var tracks: Array[Track] = [] as Array[Track]


static func from_dict(data: Dictionary) -> Animation:
	var res := Animation.new()
	if data.has("name") and data["name"] != null:
		res.name = String(data["name"])
	if data.has("length") and data["length"] != null:
		res.length = float(data["length"])
	if data.has("loop") and data["loop"] != null:
		res.loop = bool(data["loop"])
	if data.has("tracks") and data["tracks"] != null:
		res.tracks = ProscenioParseHelpers._parse_array(Track, data["tracks"])
	return res
