# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name Bone extends Resource

@export var name: String = ""
@export var parent: String = ""
@export var position: PackedFloat32Array = PackedFloat32Array()
@export var rotation: float = 0.0
@export var scale: PackedFloat32Array = PackedFloat32Array()
@export var length: float = 0.0


static func from_dict(data: Dictionary) -> Bone:
	var res := Bone.new()
	if data.has("name") and data["name"] != null:
		res.name = String(data["name"])
	if data.has("parent") and data["parent"] != null:
		res.parent = String(data["parent"])
	if data.has("position") and data["position"] != null:
		res.position = PackedFloat32Array(data["position"])
	if data.has("rotation") and data["rotation"] != null:
		res.rotation = float(data["rotation"])
	if data.has("scale") and data["scale"] != null:
		res.scale = PackedFloat32Array(data["scale"])
	if data.has("length") and data["length"] != null:
		res.length = float(data["length"])
	return res
