# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name FrameEntry extends Resource

@export var index: int = 0
@export var path: String = ""


static func from_dict(data: Dictionary) -> FrameEntry:
	var res := FrameEntry.new()
	if data.has("index"):
		res.index = int(data["index"])
	if data.has("path"):
		res.path = String(data["path"])
	return res
