# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name Key extends Resource

@export var time: float = 0.0
@export var interp: String = "linear"
@export var position: PackedFloat32Array = PackedFloat32Array()
@export var rotation: float = 0.0
@export var scale: PackedFloat32Array = PackedFloat32Array()
@export var frame: int = 0
@export var attachment: String = ""
@export var visible: bool = false


static func from_dict(data: Dictionary) -> Key:
	var res := Key.new()
	if data.has("time"):
		res.time = float(data["time"])
	if data.has("interp"):
		res.interp = String(data["interp"])
	if data.has("position"):
		res.position = PackedFloat32Array(data["position"])
	if data.has("rotation"):
		res.rotation = float(data["rotation"])
	if data.has("scale"):
		res.scale = PackedFloat32Array(data["scale"])
	if data.has("frame"):
		res.frame = int(data["frame"])
	if data.has("attachment"):
		res.attachment = String(data["attachment"])
	if data.has("visible"):
		res.visible = bool(data["visible"])
	return res
