# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name PolygonLayer extends Resource

@export var kind: String = "polygon"
@export var name: String = ""
@export var path: String = ""
@export var position: PackedInt32Array = PackedInt32Array()
@export var size: PackedInt32Array = PackedInt32Array()
@export var z_order: int = 0
@export var origin: PackedInt32Array = PackedInt32Array()
@export var blend_mode: String = "normal"
@export var subfolder: String = ""


static func from_dict(data: Dictionary) -> PolygonLayer:
	var res := PolygonLayer.new()
	if data.has("kind"):
		res.kind = String(data["kind"])
	if data.has("name"):
		res.name = String(data["name"])
	if data.has("path"):
		res.path = String(data["path"])
	if data.has("position"):
		res.position = PackedInt32Array(data["position"])
	if data.has("size"):
		res.size = PackedInt32Array(data["size"])
	if data.has("z_order"):
		res.z_order = int(data["z_order"])
	if data.has("origin"):
		res.origin = PackedInt32Array(data["origin"])
	if data.has("blend_mode"):
		res.blend_mode = String(data["blend_mode"])
	if data.has("subfolder"):
		res.subfolder = String(data["subfolder"])
	return res
