# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name PolygonSprite extends ProscenioSprite

@export var type: String = "polygon"
@export var name: String = ""
@export var bone: String = ""
@export var texture_region: PackedFloat32Array = PackedFloat32Array()
@export var polygon: Array[PackedFloat32Array] = [] as Array[PackedFloat32Array]
@export var uv: Array[PackedFloat32Array] = [] as Array[PackedFloat32Array]
@export var texture: String = ""
@export var weights: Array[Weight] = [] as Array[Weight]


static func from_dict(data: Dictionary) -> PolygonSprite:
	var res := PolygonSprite.new()
	if data.has("type"):
		res.type = String(data["type"])
	if data.has("name"):
		res.name = String(data["name"])
	if data.has("bone"):
		res.bone = String(data["bone"])
	if data.has("texture_region"):
		res.texture_region = PackedFloat32Array(data["texture_region"])
	if data.has("polygon"):
		res.polygon = ProscenioParseHelpers._parse_vec2_array(data["polygon"])
	if data.has("uv"):
		res.uv = ProscenioParseHelpers._parse_vec2_array(data["uv"])
	if data.has("texture"):
		res.texture = String(data["texture"])
	if data.has("weights"):
		res.weights = ProscenioParseHelpers._parse_array(Weight, data["weights"])
	return res
