# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioSpriteFrameSprite extends ProscenioSprite

@export var type: String = "sprite_frame"
@export var name: String = ""
@export var bone: String = ""
@export var hframes: int = 0
@export var vframes: int = 0
@export var frame: int = 0
@export var centered: bool = false
@export var texture_region: PackedFloat32Array = PackedFloat32Array()
@export var texture: String = ""
@export var offset: PackedFloat32Array = PackedFloat32Array([0.0, 0.0])


static func from_dict(data: Dictionary) -> ProscenioSpriteFrameSprite:
	var res := ProscenioSpriteFrameSprite.new()
	if data.has("type") and data["type"] != null:
		res.type = String(data["type"])
	if data.has("name") and data["name"] != null:
		res.name = String(data["name"])
	if data.has("bone") and data["bone"] != null:
		res.bone = String(data["bone"])
	if data.has("hframes") and data["hframes"] != null:
		res.hframes = int(data["hframes"])
	if data.has("vframes") and data["vframes"] != null:
		res.vframes = int(data["vframes"])
	if data.has("frame") and data["frame"] != null:
		res.frame = int(data["frame"])
	if data.has("centered") and data["centered"] != null:
		res.centered = bool(data["centered"])
	if data.has("texture_region") and data["texture_region"] != null:
		res.texture_region = PackedFloat32Array(data["texture_region"])
	if data.has("texture") and data["texture"] != null:
		res.texture = String(data["texture"])
	if data.has("offset") and data["offset"] != null:
		res.offset = PackedFloat32Array(data["offset"])
	return res
