# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioPolygonLayer extends ProscenioLayer

@export var kind: String = "polygon"
@export var name: String = ""
@export var path: String = ""
@export var position: PackedInt32Array = PackedInt32Array()
@export var size: PackedInt32Array = PackedInt32Array()
@export var z_order: int = 0
@export var origin: PackedInt32Array = PackedInt32Array()
@export var blend_mode: String = "normal"
@export var subfolder: String = ""


static func from_dict(data: Dictionary) -> ProscenioPolygonLayer:
	var res := ProscenioPolygonLayer.new()
	if data.has("kind") and data["kind"] != null:
		res.kind = String(data["kind"])
	if data.has("name") and data["name"] != null:
		res.name = String(data["name"])
	if data.has("path") and data["path"] != null:
		res.path = String(data["path"])
	if data.has("position") and data["position"] != null:
		res.position = PackedInt32Array(data["position"])
	if data.has("size") and data["size"] != null:
		res.size = PackedInt32Array(data["size"])
	if data.has("z_order") and data["z_order"] != null:
		res.z_order = int(data["z_order"])
	if data.has("origin") and data["origin"] != null:
		res.origin = PackedInt32Array(data["origin"])
	if data.has("blend_mode") and data["blend_mode"] != null:
		res.blend_mode = String(data["blend_mode"])
	if data.has("subfolder") and data["subfolder"] != null:
		res.subfolder = String(data["subfolder"])
	return res
