# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioDocument extends Resource

@export var format_version: int = 1
@export var name: String = ""
@export var pixels_per_unit: float = 0.0
@export var skeleton: Skeleton = null
@export var sprites: Array[ProscenioSprite] = [] as Array[ProscenioSprite]
@export var slots: Array[Slot] = [] as Array[Slot]
@export var atlas: String = ""
@export var animations: Array[Animation] = [] as Array[Animation]


static func from_dict(data: Dictionary) -> ProscenioDocument:
	var res := ProscenioDocument.new()
	if data.has("format_version"):
		res.format_version = int(data["format_version"])
	if data.has("name"):
		res.name = String(data["name"])
	if data.has("pixels_per_unit"):
		res.pixels_per_unit = float(data["pixels_per_unit"])
	if data.has("skeleton"):
		res.skeleton = Skeleton.from_dict(data["skeleton"])
	if data.has("sprites"):
		res.sprites = ProscenioParseHelpers._parse_dispatched(ProscenioSprite, data["sprites"])
	if data.has("slots"):
		res.slots = ProscenioParseHelpers._parse_array(Slot, data["slots"])
	if data.has("atlas"):
		res.atlas = String(data["atlas"])
	if data.has("animations"):
		res.animations = ProscenioParseHelpers._parse_array(Animation, data["animations"])
	return res
