# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioKey extends Resource

@export var time: float = 0.0
@export var interp: String = "linear"
@export var position: PackedFloat32Array = PackedFloat32Array()
@export var rotation: float = 0.0
@export var scale: PackedFloat32Array = PackedFloat32Array()
@export var frame: int = 0
@export var attachment: String = ""
@export var visible: bool = false


static func from_dict(data: Dictionary) -> ProscenioKey:
	var res := ProscenioKey.new()
	if data.has("time") and data["time"] != null:
		res.time = float(data["time"])
	if data.has("interp") and data["interp"] != null:
		res.interp = String(data["interp"])
	if data.has("position") and data["position"] != null:
		res.position = PackedFloat32Array(data["position"])
	if data.has("rotation") and data["rotation"] != null:
		res.rotation = float(data["rotation"])
	if data.has("scale") and data["scale"] != null:
		res.scale = PackedFloat32Array(data["scale"])
	if data.has("frame") and data["frame"] != null:
		res.frame = int(data["frame"])
	if data.has("attachment") and data["attachment"] != null:
		res.attachment = String(data["attachment"])
	if data.has("visible") and data["visible"] != null:
		res.visible = bool(data["visible"])
	return res
