# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioLayer extends Resource

# Discriminated union dispatcher. Inspect the input dictionary's
# `kind` key and delegate to the matching variant
# class. Used by the importer when building child sprites/layers from
# the parsed JSON document.


static func from_dict(data: Dictionary) -> Resource:
	var tag: String = String(data.get("kind", ""))
	if tag == "polygon":
		return PolygonLayer.from_dict(data)
	if tag == "mesh":
		return PolygonLayer.from_dict(data)
	if tag == "sprite_frame":
		return SpriteFrameLayer.from_dict(data)
	push_error("unknown ProscenioLayer tag: " + tag)
	return null
