# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioSkeleton extends Resource

@export var bones: Array[ProscenioBone] = [] as Array[ProscenioBone]


static func from_dict(data: Dictionary) -> ProscenioSkeleton:
	var res := ProscenioSkeleton.new()
	if data.has("bones") and data["bones"] != null:
		res.bones = ProscenioParseHelpers._parse_array(ProscenioBone, data["bones"])
	return res
