# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioPolygonSprite extends ProscenioSprite

@export var type: String = "polygon"
@export var name: String = ""
@export var bone: String = ""
@export var texture_region: PackedFloat32Array = PackedFloat32Array()
@export var polygon: Array[PackedFloat32Array] = [] as Array[PackedFloat32Array]
@export var uv: Array[PackedFloat32Array] = [] as Array[PackedFloat32Array]
@export var texture: String = ""
@export var weights: Array[ProscenioWeight] = [] as Array[ProscenioWeight]


static func from_dict(data: Dictionary) -> ProscenioPolygonSprite:
	var res := ProscenioPolygonSprite.new()
	if data.has("type") and data["type"] != null:
		res.type = String(data["type"])
	if data.has("name") and data["name"] != null:
		res.name = String(data["name"])
	if data.has("bone") and data["bone"] != null:
		res.bone = String(data["bone"])
	if data.has("texture_region") and data["texture_region"] != null:
		res.texture_region = PackedFloat32Array(data["texture_region"])
	if data.has("polygon") and data["polygon"] != null:
		res.polygon = ProscenioParseHelpers._parse_vec2_array(data["polygon"])
	if data.has("uv") and data["uv"] != null:
		res.uv = ProscenioParseHelpers._parse_vec2_array(data["uv"])
	if data.has("texture") and data["texture"] != null:
		res.texture = String(data["texture"])
	if data.has("weights") and data["weights"] != null:
		res.weights = ProscenioParseHelpers._parse_array(ProscenioWeight, data["weights"])
	return res
