# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name ProscenioSlot extends Resource

@export var name: String = ""
@export var attachments: PackedStringArray = PackedStringArray()
@export var bone: String = ""
@export var default: String = ""


static func from_dict(data: Dictionary) -> ProscenioSlot:
	var res := ProscenioSlot.new()
	if data.has("name") and data["name"] != null:
		res.name = String(data["name"])
	if data.has("attachments") and data["attachments"] != null:
		res.attachments = PackedStringArray(data["attachments"])
	if data.has("bone") and data["bone"] != null:
		res.bone = String(data["bone"])
	if data.has("default") and data["default"] != null:
		res.default = String(data["default"])
	return res
