# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name PsdManifest extends Resource

@export var format_version: int = 2
@export var doc: String = ""
@export var size: PackedInt32Array = PackedInt32Array()
@export var pixels_per_unit: float = 0.0
@export var anchor: PackedInt32Array = PackedInt32Array()
@export var layers: Array[ProscenioLayer] = [] as Array[ProscenioLayer]


static func from_dict(data: Dictionary) -> PsdManifest:
	var res := PsdManifest.new()
	if data.has("format_version"):
		res.format_version = int(data["format_version"])
	if data.has("doc"):
		res.doc = String(data["doc"])
	if data.has("size"):
		res.size = PackedInt32Array(data["size"])
	if data.has("pixels_per_unit"):
		res.pixels_per_unit = float(data["pixels_per_unit"])
	if data.has("anchor"):
		res.anchor = PackedInt32Array(data["anchor"])
	if data.has("layers"):
		res.layers = ProscenioParseHelpers._parse_dispatched(ProscenioLayer, data["layers"])
	return res
