# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name Skeleton extends Resource

@export var bones: Array[Bone] = [] as Array[Bone]


static func from_dict(data: Dictionary) -> Skeleton:
	var res := Skeleton.new()
	if data.has("bones"):
		res.bones = ProscenioParseHelpers._parse_array(Bone, data["bones"])
	return res
