# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name Slot extends Resource

@export var name: String = ""
@export var attachments: PackedStringArray = PackedStringArray()
@export var bone: String = ""
@export var default: String = ""


static func from_dict(data: Dictionary) -> Slot:
	var res := Slot.new()
	if data.has("name"):
		res.name = String(data["name"])
	if data.has("attachments"):
		res.attachments = PackedStringArray(data["attachments"])
	if data.has("bone"):
		res.bone = String(data["bone"])
	if data.has("default"):
		res.default = String(data["default"])
	return res
