# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name SpriteFrameLayer extends Resource

@export var kind: String = "sprite_frame"
@export var name: String = ""
@export var position: PackedInt32Array = PackedInt32Array()
@export var size: PackedInt32Array = PackedInt32Array()
@export var z_order: int = 0
@export var frames: Array[FrameEntry] = [] as Array[FrameEntry]
@export var origin: PackedInt32Array = PackedInt32Array()
@export var blend_mode: String = "normal"
@export var subfolder: String = ""


static func from_dict(data: Dictionary) -> SpriteFrameLayer:
	var res := SpriteFrameLayer.new()
	if data.has("kind"):
		res.kind = String(data["kind"])
	if data.has("name"):
		res.name = String(data["name"])
	if data.has("position"):
		res.position = PackedInt32Array(data["position"])
	if data.has("size"):
		res.size = PackedInt32Array(data["size"])
	if data.has("z_order"):
		res.z_order = int(data["z_order"])
	if data.has("frames"):
		res.frames = ProscenioParseHelpers._parse_array(FrameEntry, data["frames"])
	if data.has("origin"):
		res.origin = PackedInt32Array(data["origin"])
	if data.has("blend_mode"):
		res.blend_mode = String(data["blend_mode"])
	if data.has("subfolder"):
		res.subfolder = String(data["subfolder"])
	return res
