# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name SpriteFrameSprite extends Resource

@export var type: String = "sprite_frame"
@export var name: String = ""
@export var bone: String = ""
@export var hframes: int = 0
@export var vframes: int = 0
@export var frame: int = 0
@export var centered: bool = false
@export var texture_region: PackedFloat32Array = PackedFloat32Array()
@export var texture: String = ""
@export var offset: PackedFloat32Array = PackedFloat32Array([0.0, 0.0])


static func from_dict(data: Dictionary) -> SpriteFrameSprite:
	var res := SpriteFrameSprite.new()
	if data.has("type"):
		res.type = String(data["type"])
	if data.has("name"):
		res.name = String(data["name"])
	if data.has("bone"):
		res.bone = String(data["bone"])
	if data.has("hframes"):
		res.hframes = int(data["hframes"])
	if data.has("vframes"):
		res.vframes = int(data["vframes"])
	if data.has("frame"):
		res.frame = int(data["frame"])
	if data.has("centered"):
		res.centered = bool(data["centered"])
	if data.has("texture_region"):
		res.texture_region = PackedFloat32Array(data["texture_region"])
	if data.has("texture"):
		res.texture = String(data["texture"])
	if data.has("offset"):
		res.offset = PackedFloat32Array(data["offset"])
	return res
