# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name Track extends Resource

@export var type: String = "bone_transform"
@export var target: String = ""
@export var keys: Array[Key] = [] as Array[Key]


static func from_dict(data: Dictionary) -> Track:
	var res := Track.new()
	if data.has("type"):
		res.type = String(data["type"])
	if data.has("target"):
		res.target = String(data["target"])
	if data.has("keys"):
		res.keys = ProscenioParseHelpers._parse_array(Key, data["keys"])
	return res
