# AUTO-GENERATED by proscenio-codegen from packages/models/.
# Do not edit by hand; edit the pydantic models and re-run
# `python -m proscenio_codegen godot`.

@tool
class_name Weight extends Resource

@export var bone: String = ""
@export var values: PackedFloat32Array = PackedFloat32Array()


static func from_dict(data: Dictionary) -> Weight:
	var res := Weight.new()
	if data.has("bone") and data["bone"] != null:
		res.bone = String(data["bone"])
	if data.has("values") and data["values"] != null:
		res.values = PackedFloat32Array(data["values"])
	return res
